all:
  hosts:
    k8s-k00:
      ansible_host: 192.168.30.50
      etcd_member_name: etcd0
    k8s-k01:
      ansible_host: 192.168.30.51
      etcd_member_name: etcd1
    k8s-k02:
      ansible_host: 192.168.30.52
      etcd_member_name: etcd2
    k8s-k03:
      ansible_host: 192.168.30.53
      etcd_member_name: etcd3
    k8s-k04:
      ansible_host: 192.168.30.54
      etcd_member_name: etcd4
    k8s-k05:
      ansible_host: 192.168.30.55
      etcd_member_name: etcd5
    k8s-k06:
      ansible_host: 192.168.30.56
      etcd_member_name: etcd6
    k8s-k07:
      ansible_host: 192.168.30.57
      etcd_member_name: etcd7
    k8s-k08:
      ansible_host: 192.168.30.58
      etcd_member_name: etcd8
    k8s-k09:
      ansible_host: 192.168.30.59
      etcd_member_name: etcd9
  children:
    kube_control_plane:
      hosts:
        k8s-k00:
        k8s-k05:
        k8s-k08:
    kube_node:
      hosts:
        k8s-k01:
        k8s-k02:
        k8s-k03:
        k8s-k04:
        k8s-k06:
        k8s-k07:
        k8s-k09:
    etcd:
      hosts:
        k8s-k00:
        k8s-k05:
        k8s-k08:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
